#/bin/sh
#
h2xml -I /usr/include/ImageMagick/ /usr/include/ImageMagick/wand/MagickWand.h /usr/include/ImageMagick/wand/*h -o api.xml -q -c
xml2py api.xml -l /usr/lib/libMagickWand.so.3 -k f -o api.py

# Notes on API generation:
#
# * h2xml.py generates XML for primitive C types. These definitions are contained
#   in ctypes and should be removed. If not, the resulting api.py will be twice
#   as big as necessary.
# * A few numeric constants generated by h2xml.py are appended with a 'u',
#   presumably for unsigned. These will have to be fixed as they cause xml2py.py
#   to exit with an error.
# * xml2py.py only outputs method names in the XML input which are also present
#   in the LD_LIBRARY_PATH or from a library passed as a parameter. This means
#   that an up-to-date library must be present, most likely compiled from the
#   most recent source.
# * If an api.py is generated from the latest library output, many methods
#   contained within it will not be present in older versions. As such, they may
#   cause an exception when api.py is parsed, regardless of whether the missing
#   method is actually used. 
#

# eof.
